### PR TITLE
Migrate IRC presence to Libera Chat

### PR DESCRIPTION
**Pull request by rwanyoike**
See: https://github.com/nairobilug/nairobilug.or.ke/issues/193

### CODE REVIEW

**Comment by adrianteri** [comment]
I notice `nlug_matterbot` is not a bot but a *normal* user on Freenode? If this is the case the `nlug_matterbot` nick needs to be created and registered ASAP on libera.

 I'm  guessing there is a private version of this config with the bot's pass?

**Comment by rwanyoike** [comment]
Yes; `nlug_matterbot` connects as a normal user on irc. i believe there's no "bot" concept in the irc spec, and all bots connect like that. i never bothered to register the nick on freenode, so no pass was set - it was connecting anonymously.

Yes. there's a private config version, with the discord/telegram credentials filled in.

**Comment by adrianteri** [comment]
> i never bothered to register the nick on freenode, so no pass was set - it was connecting anonymously.
> 
I mean now we have discussed it's only a matter of time somebody registers the nick ...Might seem paranoid but it might lead to the bot not working and a cat and mouse game of naming ..nlug_matterbot0, nlug_matterbot1, nlug_matterbotOriginal ....etc

**Comment by rwanyoike** [comment]
Yes. I'll check the bot docs to see how to set IRC credentials. We can use "nairobilug [katika] gmail.com" to register the nick.

**Pull request closed without merging**
